### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by michelefioretti** [b-rodrigues/diffindiff#1]
Hello, I have a problem installing this package

```
library(devtools)
remotes::install_github("b-rodrigues/diffindiff")
Using github PAT from envvar GITHUB_TOKEN
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 37/60
  Rate limit reset at: 2022-11-07 12:12:17 UTC
```

Could you please help me with this error? (R version 3.6.1, mac OS Monterey v12.4). Thank you so much.

**Comment by b-rodrigues** [comment]
Hello

I have not worked on this package for years, and never actually finished it. In its current stat this package only contains the data from the original paper. However, you should be able to install it with the command you tried, but I see that your R version is quite old, maybe that’s related. Update it to the latest version (R 4.2) and try again. If you’re interested in diff in diff methods and want a more robust and recent package, take a look at {did}

https://www.rdocumentation.org/packages/did/versions/2.1.2

Cheers

**Comment by michelefioretti** [comment]
Thank you for your prompt reply. Is there a way to download the dataset without installing the package? I updated R but I still get the same error

**Comment by michelefioretti** [comment]
Thank you for the quick help!

**Comment by b-rodrigues** [comment]
yep, the data is right here

https://github.com/b-rodrigues/diffindiff/tree/master/data

you should be able to read it in using load()
